

#         Powered by TabooLib 5.0         #


Durability:
  display: '&8[ &f%symbol% &8]'
  display-symbol:
    0: ◆
    1: ◇

InternetItem:
  item:
  # - https://.../item-internet.yml
  display:
  # - https://.../display-internet.yml