

#         Powered by TabooLib 6.0         #


Database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: minecraft
  prefix: zaphkiel

Durability:
  display: '&8[ &f%symbol% &8]'
  display-symbol:
    0: ◆
    1: ◇

InternetItem:
  item: []
  # - https://.../item-internet.yml
  display: []
  # - https://.../display-internet.yml